version: '3.8'

volumes: 
    pg-data:
      external: true

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: exemple
      POSTGRES_USER: exemple
      POSTGRES_DB: exemple # DEFAULT DATABASE
    volumes:
      - pg-data:/var/lib/postgresql/data:rw
    ports:
     - ${POSTGRES_PORT}:5432

  app-dev:
    container_name: app-dev
    image: ${APP_NAME}:latest
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - "postgres"

  # sonarqube:
  #   container_name: sonarqube
  #   image: sonarqube:latest
  #   ports:
  #     - "9000:9000"
  #     - "9092:9092"

